<!DOCTYPE html>
<!-- YW: We will be using "Z" pattern -->
<!-- YW: Font Suggestion - I think it is good to use modern or computer-like pixelated
fonts since all the students share one common thing, being a CS major. -->
<html lang="en">
      <head>
            <meta charset="utf-8">
            <title><?php echo $currentTitle ?></title>
            <!--YW: CSS links -->  
			<link rel="stylesheet" type="text/css" href="./css/navigation.css">
			<link rel="stylesheet" type="text/css" href="./css/styles.css">
			<link rel="stylesheet" href="sss/sss.css">
            <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
      </head>
      <body>
