<!DOCTYPE html>
<html lang="en">
      <head>
            <meta charset="utf-8">
            <title><?php echo $currentTitle ?></title>  
			<link rel="stylesheet" type="text/css" href="./css/navigation.css">
			<link rel="stylesheet" type="text/css" href="./css/styles.css">
			<link rel="stylesheet" href="sss/sss.css">
            <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
      </head>
      <body>
